spring:
  datasource:
    url: jdbc:mysql://localhost:3306/electricity_system?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: zx20010208
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

